---
title: "Untitled"
output: html_document
---

```{r}
library(readr)
library(dplyr)

library(car)
library(plyr)
library(ipumsr)
library(labelled)
library(ggplot2)
library(mosaic)



usa_ddi <- read_ipums_ddi("/home/pelayo1/ImmigrationDUR/American Dream/usa_00008.xml")
usa_data <- read_ipums_micro(usa_ddi, verbose = FALSE)
usa_data <- usa_data %>%
  mutate(METRO = droplevels(as_factor(METRO)), BIRTHPLACE_factor= droplevels(as_factor(BPL)), LABFORCE1= droplevels(as_factor(LABFORCE)), SEX= droplevels(as_factor(SEX)),FOODSTMP= droplevels(as_factor(FOODSTMP)), RELATE= droplevels(as_factor(RELATE)),RELATED= droplevels(as_factor(RELATED)), MARST= droplevels(as_factor(MARST)), BPL = droplevels(as_factor(BPL)),BPLD = droplevels(as_factor(BPLD)), CITIZEN = droplevels(as_factor(CITIZEN)),RACESING=droplevels.factor(RACESING),RACESINGD=droplevels(as_factor(RACESINGD)),HCOVANY = droplevels(as_factor(HCOVANY)),HCOPRIV = droplevels(as_factor(HCOVPRIV)), EDUCATION = droplevels(as_factor(GRADEATT)),EDUCATIOND= droplevels(as_factor(GRADEATTD)),EMPLOYMENT = droplevels(as_factor(EMPSTAT)), EMPLOYMENTD = droplevels(as_factor(EMPSTATD)), LABFORCE = droplevels(as_factor(LABFORCE)), IND = droplevels(as_factor(IND)),
 CLASSWKR = droplevels(as_factor(CLASSWKR)), CLASSWKRD = droplevels(as_factor(CLASSWKRD)), POVERTY = droplevels(as_factor(POVERTY)), MIGRATE1 = droplevels(as_factor(MIGRATE1)), MIGRATE1D = droplevels(as_factor(MIGRATE1D)), MIGPLAC1 = droplevels(as_factor(MIGPLAC1)), TRANWORK = droplevels(as_factor(TRANWORK)), OWNERSHP  = droplevels(as_factor(OWNERSHP)), HCOVPRIV1 = droplevels(as_factor(HCOVPRIV)), RACE= droplevels(as_factor(RACESING)))
usa_data$BPLD <-recode_factor(usa_data$BPLD, 'Egypt/United Arab Rep.' = "Egypt/UAE", 'Yemen Arab Republic (North)' = "Yemen")
usa_data$EMPLOYMENT <-recode_factor(usa_data$EMPLOYMENT, 'N/A' = "Armed Forces")
usa_data$LABFORCE1<-recode_factor(usa_data$LABFORCE1,'Yes, in the labor force'= "Yes",'No, not in the labor force'="No") 
usa_data$METRO<-recode_factor(usa_data$METRO,'Central / Principal city status unknown' = " Metro area, central", 'In metro area, central / principal city' = " Metro area, central",'In metro area, outside central / principal city' ="Metro area, outside central")
usa_data$OWNERSHP <-recode_factor(usa_data$OWNERSHP, 'Owned or being bought (loan)' = "Own", 'Rented' = "Rent")
usa_data <- usa_data %>% filter(YRIMMIG >1995,AGE >= 25)
usa_data$YRSINUSA <- usa_data$YEAR - usa_data$YRIMMIG
usa_data <- usa_data[usa_data$OWNERSHP != "0",]
usa_data$POVERTY <- as.numeric(usa_data$POVERTY)
usa_data <- usa_data[!is.na(usa_data$HCOVANY),]
usa_data <- usa_data %>% mutate(YRGROUP = ifelse(YRSINUSA <= 5,"0-5",
                                    ifelse(YRSINUSA >5 & YRSINUSA <=10, "6-10",
                                   ifelse(YRSINUSA >10 & YRSINUSA <=15, "11-15",
                                    ifelse(YRSINUSA >15, ">15", "N/A")))),
                                Employment = ifelse(EMPLOYMENT == "Employed", 1,0), 
                              Laborforce = ifelse(LABFORCE1=="Yes",1,0),
                              Residence = ifelse(METRO == "Metro area, outside central",1,0), 
                              Ownhome = ifelse(OWNERSHP=="Own",1,0),
                              Poverty = ifelse(POVERTY >150, 1,0),
                              Health = ifelse(HCOVPRIV1 == "With private health insurance coverage", 1, 0),
                              Foodstamp = ifelse(FOODSTMP=="No",1,0),
                              Race = ifelse(RACE==1,"White","Non-white"))

table(usa_data$CITIZEN)

```

```{r}
### Best Subsets
library(leaps)
?regsubsets

bestss <- regsubsets(Ownhome ~ FOODSTMP + FAMSIZE + SEX + AGE + MARST + BPLD + CITIZEN + YRIMMIG + HCOVANY + LABFORCE +INCTOT + POVERTY + MIGRATE1 + EMPLOYMENT + YRSINUSA, data = usa_data, method = "exhaustive", nbest = 3)
summary.bestss <- summary(bestss, matrix.logical = TRUE) # matrix.logical term makes table of included terms more readable
summary.bestss
coef(bestss, 1:15)

plot(bestss, scale = "adjr2", main = "Adjusted R^2")
plot(bestss, scale = "Cp", main = "Mallow's Cp")

# Which model has best adjusted R^2
which.max(summary.bestss$adjr2)
summary.bestss$which[7,]

# Which model has best Mallow's Cp
which.min(summary.bestss$cp)
summary.bestss$which[7,]

#best.lm <- lm(Mass ~ BillDepth + BillLength + Skull + Sex, data = bird.df)
#summary(best.lm)

# Forwards / Backwards / Stepwise 
# Using AIC not p-value

?step


m2 <- glm(Ownhome ~ FOODSTMP + FAMSIZE + SEX + BPLD + CITIZEN + YRIMMIG + POVERTY + MIGRATE1 + LABFORCE, family = binomial(link = "logit"), data = usa_data)
summary(m2)
exp(m2$coefficients)
1-pchisq(m2$deviance,m2$df.residual)
exp(m2)
AIC(m2)
exp(confint(m2))
vif(m2)

prop.table(table(usa_data$Ownhome, usa_data$BPLD),2 )

mosaicplot(prop.table(table(usa_data$Ownhome, usa_data$BPLD)), color=TRUE,main="OWNHOME VS BIRTHPLACE")


prop.table(table(usa_data$FOODSTMP, usa_data$Ownhome),2)
prop.table(table(usa_data$CITIZEN, usa_data$Ownhome),2)

library(plotly)

ggplotly(ggplot(usa_data, aes(x=as.factor(Ownhome), y=POVERTY)) + geom_boxplot() + xlab("OWN") + ylab("Poverty Score"))



#pred <- data.frame(GPA = c(2.9, 4.0))

# B0 + B1*X
#predict(m2, newdata = pred)
# Probabilities
#predict(m2, newdata = pred, type = "response")

#m3 <- glm(Ownhome ~ POVERTY, family = binomial(link = "logit"), data = usa_data)
#summary(m3)

#pred.pov <- data.frame(POVERTY = seq(2, 4, length = 1000))
#pihat <- predict(m3, pred.pov, type = "response")

#plot(pihat~pred.pov[,1],type="l")


```


