---
title: "IRT"
output: html_document
---

IRT
```{r}
library(readr)
library(lattice)
library(mosaic)
library(car)
library(tidyverse)
library(data.table)
library(ipumsr)
library(labelled)

usa_ddi <- read_ipums_ddi("usa_00008.xml") 
usa_data <- read_ipums_micro(usa_ddi, verbose = FALSE) #Immigrant dataset

#relabelling variables
usa_data <- usa_data %>%
  mutate(METRO = droplevels(as_factor(METRO)), BIRTHPLACE_factor= droplevels(as_factor(BPL)), LABFORCE1= droplevels(as_factor(LABFORCE)), SEX= droplevels(as_factor(SEX)),FOODSTMP= droplevels(as_factor(FOODSTMP)), RELATE= droplevels(as_factor(RELATE)),RELATED= droplevels(as_factor(RELATED)), MARST= droplevels(as_factor(MARST)), BPL = droplevels(as_factor(BPL)),BPLD = droplevels(as_factor(BPLD)), CITIZEN = droplevels(as_factor(CITIZEN)),RACESING=droplevels.factor(RACESING),RACESINGD=droplevels(as_factor(RACESINGD)),HCOVANY = droplevels(as_factor(HCOVANY)),HCOPRIV = droplevels(as_factor(HCOVPRIV)), EDUCATION = droplevels(as_factor(GRADEATT)),EDUCATIOND= droplevels(as_factor(GRADEATTD)),EMPLOYMENT = droplevels(as_factor(EMPSTAT)), EMPLOYMENTD = droplevels(as_factor(EMPSTATD)), LABFORCE = droplevels(as_factor(LABFORCE)), IND = droplevels(as_factor(IND)),
 CLASSWKR = droplevels(as_factor(CLASSWKR)), CLASSWKRD = droplevels(as_factor(CLASSWKRD)), POVERTY = droplevels(as_factor(POVERTY)), MIGRATE1 = droplevels(as_factor(MIGRATE1)), MIGRATE1D = droplevels(as_factor(MIGRATE1D)), MIGPLAC1 = droplevels(as_factor(MIGPLAC1)), TRANWORK = droplevels(as_factor(TRANWORK)), OWNERSHP  = droplevels(as_factor(OWNERSHP)), HCOVPRIV1 = droplevels(as_factor(HCOVPRIV)), RACE= droplevels(as_factor(RACESING)))

usa_data$BPLD <-recode_factor(usa_data$BPLD, 'Yemen Arab Republic (North)' = "Yemen")
usa_data$EMPLOYMENT <-recode_factor(usa_data$EMPLOYMENT, 'N/A' = "Armed Forces")
usa_data$LABFORCE1<-recode_factor(usa_data$LABFORCE1,'Yes, in the labor force'= "Yes",'No, not in the labor force'="No") 
usa_data$METRO<-recode_factor(usa_data$METRO,'Central / Principal city status unknown' = " Metro area, central", 'In metro area, central / principal city' = " Metro area, central",'In metro area, outside central / principal city' ="Metro area, outside central")
usa_data$OWNERSHP <-recode_factor(usa_data$OWNERSHP, 'Owned or being bought (loan)' = "Own", 'Rented' = "Rent")
usa_data <- usa_data[usa_data$OWNERSHP != "0",]

usa_data$POVERTY <- as.numeric(usa_data$POVERTY)
usa_data <- usa_data[!is.na(usa_data$HCOVANY),]

###new variable, number of years spent in the US
usa_data$YRSINUSA <- usa_data$YEAR - usa_data$YRIMMIG 
usa_data <- usa_data %>% mutate(YRGROUP = ifelse(YRSINUSA <= 5,"0-5",
                                    ifelse(YRSINUSA >5 & YRSINUSA <=10, "6-10",
                                   ifelse(YRSINUSA >10 & YRSINUSA <=15, "11-15",
                                    ifelse(YRSINUSA >15, ">15", "N/A")))))

###filter by age and country
usa_data <- usa_data %>% filter(YRIMMIG >1995,AGE >= 25, 
                                BPLD !="Egypt/United Arab Rep.", 
                                BPLD !="Iraq", BPLD !="Sudan")
###new variable, age group
usa_data <- usa_data %>% mutate(AGEGROUP = ifelse(AGE >=25 & AGE <= 30,"25-30",
                                    ifelse(AGE >=31 & AGE <= 40, "31-40",
                                   ifelse(AGE >=41 & AGE <= 50, "41-50",
                                    ifelse(AGE >=51 & AGE <= 60,"51-60", 
                                    ifelse(AGE >=61,">60","N/A"))))))

###Indicator variables 
usa_data <- usa_data %>% mutate(Employment = ifelse(EMPLOYMENT == "Employed", 1,0), 
                              Laborforce = ifelse(LABFORCE1=="Yes",1,0),
                              Residence = ifelse(METRO == "Metro area, outside central",1,0), 
                              Ownhome = ifelse(OWNERSHP=="Own",1,0),
                              Poverty = ifelse(POVERTY >150, 1,0),
                              Health = ifelse(HCOVPRIV1 == "With private health insurance coverage", 1, 0),
                              Foodstamp = ifelse(FOODSTMP=="No",1,0),
                              White = ifelse(RACE==1,1,0),
                              Citizen = ifelse(CITIZEN == ' Not a citizen', 0, 1))


# Indicator for whether one is an immigrant
BP = 0
usa_data <- cbind(usa_data,BP)
```
                 
```{r}

usa_ddi1 <- read_ipums_ddi("usa_00013.xml")
usadata <- read_ipums_micro(usa_ddi1, verbose = FALSE) #Nonimmigrant dataset
usadata <-usadata %>% filter(AGE > 25)
usadata <- na.omit(usadata)

usadata <- usadata %>%
  mutate(METRO = droplevels(as_factor(METRO)), BIRTHPLACE_factor= droplevels(as_factor(BPL)), LABFORCE1= droplevels(as_factor(LABFORCE)), SEX= droplevels(as_factor(SEX)),FOODSTMP= droplevels(as_factor(FOODSTMP)), RELATE= droplevels(as_factor(RELATE)),RELATED= droplevels(as_factor(RELATED)), MARST= droplevels(as_factor(MARST)), BPL = droplevels(as_factor(BPL)),BPLD = droplevels(as_factor(BPLD)), CITIZEN = droplevels(as_factor(CITIZEN)),RACESING=droplevels.factor(RACESING),RACESINGD=droplevels(as_factor(RACESINGD)),HCOVANY = droplevels(as_factor(HCOVANY)),HCOPRIV = droplevels(as_factor(HCOVPRIV)), EDUCATION = droplevels(as_factor(GRADEATT)),EDUCATIOND= droplevels(as_factor(GRADEATTD)),EMPLOYMENT = droplevels(as_factor(EMPSTAT)), EMPLOYMENTD = droplevels(as_factor(EMPSTATD)), LABFORCE = droplevels(as_factor(LABFORCE)), IND = droplevels(as_factor(IND)),
 CLASSWKR = droplevels(as_factor(CLASSWKR)), CLASSWKRD = droplevels(as_factor(CLASSWKRD)), MIGRATE1 = droplevels(as_factor(MIGRATE1)), MIGRATE1D = droplevels(as_factor(MIGRATE1D)), MIGPLAC1 = droplevels(as_factor(MIGPLAC1)), TRANWORK = droplevels(as_factor(TRANWORK)), OWNERSHP  = droplevels(as_factor(OWNERSHP)), HCOVPRIV1 = droplevels(as_factor(HCOVPRIV)), RACE= droplevels(as_factor(RACESING)))

usadata$POVERTY = as.numeric(usadata$POVERTY)
usadata <- usadata[!is.na(usadata$HCOVPRIV1),]
usadata <- usadata[usadata$OWNERSHP != "N/A",]
usadata$LABFORCE1<-recode_factor(usadata$LABFORCE1,'Yes, in the labor force'= "Yes",'No, not in the labor force'="No") 
usadata$OWNERSHP <-recode_factor(usadata$OWNERSHP, 'Owned or being bought (loan)' = "Own", 'Rented' = "Rent")
usadata$YRSINUSA <- usadata$YEAR - usadata$YRIMMIG
usadata <- usadata %>% mutate(YRGROUP = ifelse(YRSINUSA <= 5,"0-5",
                                    ifelse(YRSINUSA >5 & YRSINUSA <=10, "6-10",
                                   ifelse(YRSINUSA >10 & YRSINUSA <=15, "11-15",
                                    ifelse(YRSINUSA >15, ">15", "N/A")))),
                              Employment = ifelse(EMPLOYMENT == "Employed", 1,0), 
                              Laborforce = ifelse(LABFORCE1=="Yes",1,0),
                              Residence = ifelse(METRO == "Metro area, outside central",1,0), 
                              Ownhome = ifelse(OWNERSHP=="Own",1,0),
                              Poverty = ifelse(POVERTY > 150, 1,0),
                              Health = ifelse(HCOVPRIV1 == "With private health insurance coverage", 1, 0),
                              Foodstamp = ifelse(FOODSTMP=="No",1,0),
                              White = ifelse(RACE==1,1,0),
                              Citizen = ifelse(CITIZEN == ' Not a citizen', 0, 1),
                              AGEGROUP = ifelse(AGE >=25 & AGE <= 30,"25-30",
                                    ifelse(AGE >=31 & AGE <= 40, "31-40",
                                   ifelse(AGE >=41 & AGE <= 50, "41-50",
                                    ifelse(AGE >=51 & AGE <= 60,"51-60", 
                                    ifelse(AGE >=61,">60","N/A"))))))

##### Non-Immigrants
set.seed(57)
samp <- data.table(usadata)
nonimm<-samp[sample(nrow(samp), 10000)] #Sample Nonimmigrant dataset
BP =1 
nonimm<- cbind(nonimm,BP)

#Final dataset
data_com<-rbind(usa_data,nonimm, fill=TRUE)
```

```{r}

######### IRT ########
#### Immigrants
data_com.subset <- data.frame(Emp= rep(data_com$Employment, data_com$PERWT),
                              Pov = rep(data_com$Poverty, data_com$PERWT),
                              Fs = rep(data_com$Foodstamp, data_com$PERWT),
                Home = rep(data_com$Ownhome,data_com$PERWT),
                Hlth = rep(data_com$Health, data_com$PERWT),
                Years = rep(data_com$YRGROUP,data_com$PERWT),
                Indicator = rep(data_com$BP, data_com$PERWT),
                Country= rep(data_com$BPLD, data_com$PERWT),
                Age = rep(data_com$AGEGROUP, data_com$PERWT))
library(ltm)
library(msm)

ADmodel <- ltm(data_com.subset[,1:4]~z1, IRT.param = T)
plot(ADmodel, main = "Success Score", type="ICC")
plot(ADmodel, type="IIC",main = "Item Information Curve")
ADmodel
```

```{r}
par(mfrow=c(2,2))

#Immigrant response curve
data_com.subset2 <- data_com.subset %>% filter(Indicator=="0")
AD1 <- ltm(data_com.subset2[,1:5]~z1, IRT.param = T)
plot(AD1, main = "Immigrant Success Score", type="ICC")
plot(AD1, type="IIC",main = "Immigrant Item Information Curve")

#Non Immigrant item response curve
data_com.subset1 <- data_com.subset %>% filter(Indicator=="1")
AD <- ltm(data_com.subset1[,1:5]~z1, IRT.param = T)
plot(AD, main = "Nonimmigrant Success Score ", type="ICC")
plot(AD, type="IIC",main = "Nonimmigrant Item Information Curve")
```

```{r}
#Item response curve by age group 25 -30

par(mfrow = c(2,2))
#Immigrant response curve
data_com.subset2a <- data_com.subset %>% filter(Indicator=="0", Age =="25-30")
AD2a <- ltm(data_com.subset2a[,1:5]~z1, IRT.param = T)
plot(AD2a, main = "Immigrant 25 -30 years Success Score", type="ICC")
plot(AD2a, type="IIC",main = "Immigrant Item Information Curve")

#Non Immigrant response curve
data_com.subset1a <- data_com.subset %>% filter(Indicator=="1", Age =="25-30")
AD1a <- ltm(data_com.subset1a[,1:5]~z1, IRT.param = T)
plot(AD1a, main = "Nonimmigrant 25-30 years Success Score ", type="ICC")
plot(AD1a, type="IIC",main = "Nonimmigrant Item Information Curve")
```

```{r}
#Item response curve by age group 31-40

par(mfrow = c(2,2))
#Immigrant response curve
data_com.subset2b <- data_com.subset %>% filter(Indicator=="0", Age =="31-40")
AD2b <- ltm(data_com.subset2b[,1:5]~z1, IRT.param = T)
plot(AD2b, main = "Immigrant 31-40 years Success Score", type="ICC")
plot(AD2b, type="IIC",main = "Immigrant Item Information Curve")

#Non Immigrant response curve
data_com.subset1b <- data_com.subset %>% filter(Indicator=="1", Age =="31-40")
AD1b <- ltm(data_com.subset1b[,1:5]~z1, IRT.param = T)
plot(AD1b, main = "Nonimmigrant 31-40 years Success Score ", type="ICC")
plot(AD1b, type="IIC",main = "Nonimmigrant Item Information Curve")
```

```{r}
#Item response curve by age group 41-50

par(mfrow = c(2,2))
#Immigrant response curve
data_com.subset2c <- data_com.subset %>% filter(Indicator=="0", Age =="41-50")
AD2c <- ltm(data_com.subset2c[,1:5]~z1, IRT.param = T)
plot(AD2c, main = "Immigrant 41-50 years Success Score", type="ICC")
plot(AD2c, type="IIC",main = "Immigrant Item Information Curve")

#Non Immigrant response curve
data_com.subset1c <- data_com.subset %>% filter(Indicator=="1", Age =="41-50")
AD1c <- ltm(data_com.subset1c[,1:5]~z1, IRT.param = T)
plot(AD1c, main = "Nonimmigrant 41-50 years Success Score ", type="ICC")
plot(AD1c, type="IIC",main = "Nonimmigrant Item Information Curve")
```

```{r}
#Item response curve by age group 51-60

par(mfrow = c(2,2))
#Immigrant response curve
data_com.subset2d <- data_com.subset %>% filter(Indicator=="0", Age =="51-60")
AD2d <- ltm(data_com.subset2d[,1:5]~z1, IRT.param = T)
plot(AD2d, main = "Immigrant 51-60 years Success Score", type="ICC")
plot(AD2d, type="IIC",main = "Immigrant Item Information Curve")

#Non Immigrant response curve
data_com.subset1d <- data_com.subset %>% filter(Indicator=="1", Age =="51-60")
AD1d <- ltm(data_com.subset1d[,1:5]~z1, IRT.param = T)
plot(AD1d, main = "Nonimmigrant 51-60 years Success Score ", type="ICC")
plot(AD1d, type="IIC",main = "Nonimmigrant Item Information Curve")
```

```{r}
#Item response curve by age group above 60

par(mfrow = c(2,2))
#Immigrant response curve
data_com.subset2e <- data_com.subset %>% filter(Indicator=="0", Age ==">60")
AD2e <- ltm(data_com.subset2e[,1:5]~z1, IRT.param = T)
plot(AD2e, main = "Immigrant above 60 years Success Score", type="ICC")
plot(AD2e, type="IIC",main = "Immigrant Item Information Curve")

#Non Immigrant response curve
data_com.subset1e <- data_com.subset %>% filter(Indicator=="1", Age ==">60")
AD1e <- ltm(data_com.subset1e[,1:5]~z1, IRT.param = T)
plot(AD1e, main = "Nonimmigrant above 60 years Success Score ", type="ICC")
plot(AD1e, type="IIC",main = "Nonimmigrant Item Information Curve")
```

```{r}
# z-score extraction
extract <-factor.scores(ADmodel)$score.dat
extract1 <-merge(data_com.subset,extract)

ggplot(extract1, aes(as.factor(Age),se.z1,fill=as.factor(Indicator)))+ 
  geom_boxplot(alpha=0.7)
```

```{r}
# We need this to interpret the IRT.
df.admod<- as.data.frame(coef(ADmodel))  #general
df.ad_non <- as.data.frame(coef(AD)) #nonimmigrant
df.ad<- as.data.frame(coef(AD1)) #immigrant
#A high discrimination parameter value suggests an item that has a high ability to differentiate subjects. Example - a high discrimination parameter value means that the probability of a correct response increases more rapidly as the ability (latent trait) increases.
```

```{r}
# z-score extraction
extract <-factor.scores(ADmodel)$score.dat

extract$Employment <-extract$Emp
extract$Poverty <-extract$Pov
extract$Foodstamp <-extract$Fs
extract$Ownhome <-extract$Home
extract$Health <-extract$Hlth

data_bestss<-merge(data_com,extract, by= c("Employment","Poverty","Foodstamp","Ownhome","Health")) #new dataset
View(data_bestss)

data_bestss$logz <- log(data_bestss$z1)

# modelling
library(leaps)
bestss <- regsubsets(z1 ~ FAMSIZE + SEX + AGE + MARST + CITIZEN + LABFORCE +INCTOT  + BP+MIGRATE1 + YRIMMIG, data = data_bestss, method = "exhaustive", nbest = 3)
summary.bestss <- summary(bestss, matrix.logical = TRUE) # matrix.logical term makes table of included terms more readable
summary.bestss
coef(bestss, 1:15)

plot(bestss, scale = "adjr2", main = "Adjusted R^2")
plot(bestss, scale = "Cp", main = "Mallow's Cp")

# Which model has best adjusted R^2
which.max(summary.bestss$adjr2)
summary.bestss$which[7,]

# Which model has best Mallow's Cp
which.min(summary.bestss$cp)
summary.bestss$which[7,]

```



```{r}
#write.csv(data_bestss, file = "data_bestss.csv")
median(data_bestss$z1)

median(data_bestss[BP==1]$z1)
median(data_bestss[BP==0]$z1)

med <- aggregate(z1 ~  as.factor(BP), data_bestss, median)


med
p <- ggplot(data_bestss, aes(x=as.factor(BP), y=z1)) + geom_boxplot() + xlab("Nonimmigrant Status") + ylab("Success Score") + ggtitle("Nonimmigrant Status vs Success Score") 
p

ggplot(data_bestss, aes(z1)) +geom_histogram(position="identity", bins = 100) + geom_density(alpha=0.6) + xlab("Success Score") + ylab("Count") + ggtitle("Overall Number of Success Scores") 

ggplot(data_bestss, aes(z1, colour = as.factor(BP))) + geom_density()+ xlab("Success Score") + ylab("Density") + ggtitle("Overall Number of Success Scores") 

p <- ggplot(data_bestss, aes(x=as.factor(BP), y=z1)) + geom_boxplot()
p

mod1 <- lm(z1 ~ FAMSIZE + SEX + MARST + LABFORCE +INCTOT  + BP + MIGRATE1, data= data_bestss)
mod2 <- lm(z1 ~  BP, data= data_bestss)
mod3 <- lm(z1 ~ FAMSIZE + SEX + MARST + LABFORCE +INCTOT  + BP, data= data_bestss)

mod4 <- lm(z1 ~  BP + BPLD, data= data_bestss)
summary(mod4)

df.vif <- as.data.frame(vif(mod1))
View(df.vif)
summary(mod1)
summary(mod2)
anova(mod1, mod2)
anova(mod1, mod3) #use mod1

```



