---
title: "Practice"
output: html_notebook
---

```{r}
states=row.names(USArrests)
names(USArrests)
apply(USArrests , 2, mean)
apply(USArrests , 2, var)

```

```{r}
 pr.out=prcomp(USArrests, scale=TRUE)
names(pr.out)
pr.out$center
pr.out$scale
pr.out$rotation
```

```{r}
dim(pr.out$x)
```
(50(n(observation)-1),4 predictor number)


```{r}
biplot(pr.out, scale=0)
```

```{r}
pr.var=pr.out$sdev ^2
pve=pr.var/sum(pr.var)
pve
```

We see that the first principal component explains 62.0 % of the variance in the data, the next principal component explains 24.7 % of the variance, and so forth.


```{r}
plot(pve, xlab="Principal Component", ylab="Proportion of Variance Explained ", ylim=c(0,1),type='b’)
```


```{r}

set.seed (2)
x=matrix(rnorm(50*2), ncol=2)
x[1:25,1]=x[1:25,1]+3
x[1:25,2]=x[1:25,2]-4
```

```{r}
km.out=kmeans(x,2,nstart=20)
```

```{r}
plot(x, col=(km.out$cluster +1), main="K-Means Clustering Results with K=2", xlab="", ylab="", pch=20, cex=2)
```

```{r}
set.seed (4)
km.out=kmeans(x,3,nstart=20)

```



```{r}
hc.complete=hclust(dist(x), method="complete")
hc.average=hclust(dist(x), method="average")
hc.single=hclust(dist(x), method="single")
```


```{r}
par(mfrow=c(1,3))
plot(hc.complete,main="Complete Linkage", xlab="", sub="",
cex =.9)

```
```{r}
x1=matrix(rnorm(64), ncol=32)
dd=as.dist(1-cor(t(x1)))
plot(hclust(dd, method="complete"), main="Complete Linkage
with Correlation -Based Distance", xlab="", sub="")

dist(x)
a=hclust(dist(x1), method="complete")
a$labels
cutree(a,2)
```




